entities_by_room:
  General:
  - person.smartcampus
  - person.code_community
  - person.daniel
  - person.climate_dashboard
  - person.noahfrank
  - update.home_assistant_supervisor_update
  - update.home_assistant_core_update
  - update.piper_update
  - update.studio_code_server_update
  - update.whisper_update
  - update.esphome_device_builder_update
  - update.speech_to_phrase_update
  - update.mosquitto_broker_update
  - update.home_assistant_operating_system_update
  - binary_sensor.remote_ui
  - stt.home_assistant_cloud
  - tts.home_assistant_cloud
  - conversation.home_assistant
  - input_number.battery_threshold
  - light.ikea_power_socket_1
  - light.ikea_power_socket_2
  - light.smart_switch_led_2
  - number.bottles
  - number.pfand
  - sensor.low_battery_devices
  - sun.sun
  - sensor.sun_next_dawn
  - sensor.sun_next_dusk
  - sensor.sun_next_midnight
  - sensor.sun_next_noon
  - sensor.sun_next_rising
  - sensor.sun_next_setting
  - tts.google_translate_en_com
  - binary_sensor.xxx_xxx_x_x_focus
  - device_tracker.xxx_xxx_x_x
  - sensor.xxx_xxx_x_x_connection_type
  - sensor.xxx_xxx_x_x_battery_level
  - sensor.xxx_xxx_x_x_ssid
  - sensor.xxx_xxx_x_x_bssid
  - sensor.xxx_xxx_x_x_battery_state
  - sensor.xxx_xxx_x_x_storage
  - sensor.xxx_xxx_x_x_sim_2
  - sensor.xxx_xxx_x_x_geocoded_location
  - sensor.xxx_xxx_x_x_sim_1
  - sensor.xxx_xxx_x_x_last_update_trigger
  - sensor.xxx_xxx_x_x_app_version
  - sensor.xxx_xxx_x_x_location_permission
  - sensor.xxx_xxx_x_x_audio_output
  - sensor.xxx_xxx_x_x_activity
  - sensor.xxx_xxx_x_x_floors_descended
  - sensor.xxx_xxx_x_x_steps
  - sensor.xxx_xxx_x_x_distance
  - sensor.xxx_xxx_x_x_floors_ascended
  - sensor.xxx_xxx_x_x_average_active_pace
  - binary_sensor.macbook_pro_21_camera_in_use
  - binary_sensor.macbook_pro_21_audio_input_in_use
  - binary_sensor.macbook_pro_21_audio_output_in_use
  - binary_sensor.macbook_pro_21_focus
  - binary_sensor.macbook_pro_21_active
  - device_tracker.macbook_pro_21
  - sensor.macbook_pro_21_internal_battery_level
  - sensor.macbook_pro_21_connection_type
  - sensor.macbook_pro_21_storage
  - sensor.macbook_pro_21_bssid
  - sensor.macbook_pro_21_internal_battery_state
  - sensor.macbook_pro_21_ssid
  - sensor.macbook_pro_21_geocoded_location
  - sensor.macbook_pro_21_active_camera
  - sensor.macbook_pro_21_active_audio_input
  - sensor.macbook_pro_21_active_audio_output
  - sensor.macbook_pro_21_displays
  - sensor.macbook_pro_21_primary_display_name
  - sensor.macbook_pro_21_frontmost_app
  - sensor.macbook_pro_21_primary_display_id
  - sensor.macbook_pro_21_last_update_trigger
  - sensor.macbook_pro_21_location_permission
  - sensor.macbook_pro_21_app_version
  - sensor.macbook_pro_21_audio_output
  - binary_sensor.macbook_pro_21_camera_in_use_2
  - binary_sensor.macbook_pro_21_audio_input_in_use_2
  - binary_sensor.macbook_pro_21_audio_output_in_use_2
  - binary_sensor.macbook_pro_21_active_2
  - binary_sensor.macbook_pro_21_focus_2
  - device_tracker.macbook_pro_db
  - sensor.macbook_pro_21_internal_battery_level_2
  - sensor.macbook_pro_21_storage_2
  - sensor.macbook_pro_21_internal_battery_state_2
  - sensor.macbook_pro_21_bssid_2
  - sensor.macbook_pro_21_ssid_2
  - sensor.macbook_pro_21_connection_type_2
  - sensor.macbook_pro_21_geocoded_location_2
  - sensor.macbook_pro_21_active_camera_2
  - sensor.macbook_pro_21_active_audio_input_2
  - sensor.macbook_pro_21_active_audio_output_2
  - sensor.macbook_pro_21_displays_2
  - sensor.macbook_pro_21_primary_display_name_2
  - sensor.macbook_pro_21_primary_display_id_2
  - sensor.macbook_pro_21_frontmost_app_2
  - sensor.macbook_pro_21_last_update_trigger_2
  - sensor.macbook_pro_21_app_version_2
  - sensor.macbook_pro_21_location_permission_2
  - sensor.macbook_pro_21_audio_output_2
  - device_tracker.daniels_ipad
  - sensor.daniels_ipad_battery_level
  - sensor.daniels_ipad_bssid
  - sensor.daniels_ipad_connection_type
  - sensor.daniels_ipad_geocoded_location
  - sensor.daniels_ipad_last_update_trigger
  - sensor.daniels_ipad_battery_state
  - sensor.daniels_ipad_storage
  - sensor.daniels_ipad_ssid
  - binary_sensor.octoprint_printing
  - binary_sensor.octoprint_printing_error
  - button.octoprint_resume_job
  - button.octoprint_pause_job
  - button.octoprint_stop_job
  - button.octoprint_shutdown_system
  - button.octoprint_reboot_system
  - button.octoprint_restart_octoprint
  - sensor.octoprint_actual_a_temp
  - sensor.octoprint_target_a_temp
  - sensor.octoprint_actual_e_temp
  - sensor.octoprint_target_e_temp
  - sensor.octoprint_actual_p_temp
  - sensor.octoprint_target_p_temp
  - sensor.octoprint_actual_w_temp
  - sensor.octoprint_target_w_temp
  - sensor.octoprint_actual_bed_temp
  - sensor.octoprint_target_bed_temp
  - sensor.octoprint_actual_tool0_temp
  - sensor.octoprint_target_tool0_temp
  - sensor.octoprint_current_state
  - sensor.octoprint_job_percentage
  - sensor.octoprint_estimated_finish_time
  - sensor.octoprint_start_time
  - camera.octoprint_camera
  - update.ha_floorplan_your_imagination_just_became_the_new_limit_update
  - update.hacs_update
  - update.template_entity_row_update
  - binary_sensor.rpi_power_status
  - sensor.backup_backup_manager_state
  - sensor.backup_next_scheduled_automatic_backup
  - sensor.backup_last_successful_automatic_backup
  - stt.faster_whisper
  - stt.speech_to_phrase
  - tts.piper
  - sensor.karl_marx_strasse_berlin_germany_air_quality_index
  - sensor.karl_marx_strasse_berlin_germany_humidity
  - sensor.karl_marx_strasse_berlin_germany_pressure
  - sensor.karl_marx_strasse_berlin_germany_temperature
  - sensor.karl_marx_strasse_berlin_germany_nitrogen_dioxide
  - sensor.karl_marx_strasse_berlin_germany_pm10
  - sensor.karl_marx_strasse_berlin_germany_pm2_5
  - sensor.karl_marx_strasse_berlin_germany_dominant_pollutant
  - sensor.pfand_hx711_value
  - select.home_assistant_voice_093f20_assistant
  - select.home_assistant_voice_093f20_finished_speaking_detection
  - select.home_assistant_voice_093f20_wake_word
  - media_player.home_assistant_voice_093f20_media_player
  - switch.home_assistant_voice_093f20_mute
  - switch.home_assistant_voice_093f20_wake_sound
  - light.home_assistant_voice_093f20_led_ring
  - event.home_assistant_voice_093f20_button_press
  - update.home_assistant_voice_093f20_home_assistant_voice_093f20
  - calendar.code_1_w_room_b_7_4
  - calendar.code_1_b_4_4
  - calendar.code_1_b_present_b_5_4
  - calendar.code_1_peace_b_3_6
  - calendar.code_1_babylon_a_1_12_conferencing_system
  - calendar.code_1_muted_a_6_40
  - calendar.code_1_pandora_a_24_36
  - calendar.code_1_ris_a_12_32
  - calendar.code_1_tet_a_11_68
  - calendar.code_1_mf_room_b_10_1
  - calendar.code_1_jungle_a_2_36
  - calendar.code_1_b_after_b_6_4
  - calendar.code_1_han_s_zimmer_b_12_1
  - calendar.birthdays
  - calendar.code_1_dark_matter_b_14_36
  - assist_satellite.home_assistant_voice_093f20_assist_satellite
  - binary_sensor.b3_occupancy_occupancy
  - binary_sensor.b4_occupancy_occupancy
  - binary_sensor.b5_occupancy
  - binary_sensor.b6_occupancy_occupancy_2
  - binary_sensor.b7_occupancy_occupancy_2
  - binary_sensor.unknown_occupancy_3
  - binary_sensor.b12_occupancy_occupancy_3
  - binary_sensor.a6_occupancy_occupancy_4
  - binary_sensor.ewelink_ms01
  - binary_sensor.ewelink_ms01_2
  - binary_sensor.unk_manufacturer_unk_model
  - binary_sensor.ewelink_ms01_3
  - button.ikea_power_socket_1_identify
  - button.ikea_aq_sensor_identify
  - button.ikea_tradfri_driver_1_identify
  - button.ikea_tradfri_driver_2_identify_2
  - button.ikea_of_sweden_remote_control_n2_identify
  - button.ikea_power_socket_2_identify
  - button.sonoff_snzb_02d_temp_humidity_identify
  - button.sonoff_snzb_02d_humid_temp_identify
  - button.sonoff_snzb_02d_temp_humid_identify
  - button.sonoff_snzb_02d_identify
  - button.ikea_power_socket_identify
  - button.sonoff_snzb_02d_humid_temp_identify_2
  - button.sonoff_snzb_02d_identify_2
  - button.ikea_of_sweden_tretakt_smart_plug_identify
  - button.al001_wg001_z01_wifi_extender_identify
  - button.sonoff_snzb_02d_humid_temp_identify_3
  - button.sonoff_snzb_02d_identify_3
  - button.ikea_of_sweden_tradfri_driver_30w_3_identify
  - button.ikea_tradfri_driver_4_laser_cutter_identify
  - button.ikea_tradfri_driver_4_identify
  - button.b3_occupancy_identify
  - button.sonoff_snzb_02d_identify_4
  - button.b4_occupancy_identify
  - button.sonoff_snzb_06p_identify
  - button.b6_occupancy_identify_2
  - button.b7_occupancy_identify_2
  - button.unknown_identify_3
  - button.b12_occupancy_identify_3
  - button.a6_occupancy_identify_4
  - button.smart_switch_led_2_identify_2
  - button.ewelink_ms01_identify
  - button.frient_a_s_aqszb_110_identify
  - button.ewelink_ms01_identify_2
  - button.unk_manufacturer_unk_model_identify
  - button.ewelink_ms01_identify_3
  - light.ikea_tradfri_driver_1_light
  - light.ikea_tradfri_driver_2_light_2
  - light.ikea_of_sweden_tradfri_driver_30w_3_light
  - light.ikea_tradfri_driver_4_laser_cutter_light
  - light.ikea_tradfri_driver_4_light
  - number.ikea_tradfri_driver_1_on_off_transition_time
  - number.ikea_tradfri_driver_1_on_level
  - number.ikea_tradfri_driver_1_start_up_current_level
  - number.ikea_tradfri_driver_2_on_off_transition_time_2
  - number.ikea_tradfri_driver_2_on_level_2
  - number.ikea_tradfri_driver_2_start_up_current_level_2
  - number.sonoff_snzb_02d_temp_humidity_comfort_temperature_min
  - number.sonoff_snzb_02d_temp_humidity_comfort_temperature_max
  - number.sonoff_snzb_02d_temp_humidity_comfort_humidity_min
  - number.sonoff_snzb_02d_temp_humidity_comfort_humidity_max
  - number.sonoff_snzb_02d_humid_temp_comfort_temperature_min
  - number.sonoff_snzb_02d_humid_temp_comfort_temperature_max
  - number.sonoff_snzb_02d_humid_temp_comfort_humidity_min
  - number.sonoff_snzb_02d_humid_temp_comfort_humidity_max
  - number.sonoff_snzb_02d_temp_humid_comfort_temperature_min
  - number.sonoff_snzb_02d_temp_humid_comfort_temperature_max
  - number.sonoff_snzb_02d_temp_humid_comfort_humidity_min
  - number.sonoff_snzb_02d_temp_humid_comfort_humidity_max
  - number.sonoff_snzb_02d_humid_temp_comfort_temperature_min_2
  - number.sonoff_snzb_02d_humid_temp_comfort_temperature_max_2
  - number.sonoff_snzb_02d_humid_temp_comfort_humidity_min_2
  - number.sonoff_snzb_02d_humid_temp_comfort_humidity_max_2
  - number.sonoff_snzb_02d_humid_temp_comfort_temperature_min_3
  - number.sonoff_snzb_02d_humid_temp_comfort_temperature_max_3
  - number.sonoff_snzb_02d_humid_temp_comfort_humidity_min_3
  - number.sonoff_snzb_02d_humid_temp_comfort_humidity_max_3
  - number.sonoff_snzb_02d_humid_temp_comfort_temperature_min_4
  - number.sonoff_snzb_02d_humid_temp_comfort_temperature_max_4
  - number.sonoff_snzb_02d_humid_temp_comfort_humidity_min_4
  - number.sonoff_snzb_02d_humid_temp_comfort_humidity_max_4
  - number.sonoff_snzb_02d_humid_temp_comfort_temperature_min_5
  - number.sonoff_snzb_02d_humid_temp_comfort_temperature_max_5
  - number.sonoff_snzb_02d_humid_temp_comfort_humidity_min_5
  - number.sonoff_snzb_02d_humid_temp_comfort_humidity_max_5
  - number.sonoff_snzb_02d_humid_temp_comfort_temperature_min_6
  - number.sonoff_snzb_02d_humid_temp_comfort_temperature_max_6
  - number.sonoff_snzb_02d_humid_temp_comfort_humidity_min_6
  - number.sonoff_snzb_02d_humid_temp_comfort_humidity_max_6
  - number.ikea_of_sweden_tradfri_driver_30w_3_on_off_transition_time
  - number.ikea_of_sweden_tradfri_driver_30w_3_on_level
  - number.ikea_of_sweden_tradfri_driver_30w_3_start_up_current_level
  - number.ikea_tradfri_driver_4_laser_cutter_on_off_transition_time
  - number.ikea_tradfri_driver_4_laser_cutter_on_level
  - number.ikea_tradfri_driver_4_laser_cutter_start_up_current_level
  - number.ikea_tradfri_driver_4_on_off_transition_time
  - number.ikea_tradfri_driver_4_on_level
  - number.ikea_tradfri_driver_4_start_up_current_level
  - number.b3_occupancy_presence_detection_timeout
  - number.sonoff_snzb_02d_comfort_temperature_min
  - number.sonoff_snzb_02d_comfort_temperature_max
  - number.sonoff_snzb_02d_comfort_humidity_min
  - number.sonoff_snzb_02d_comfort_humidity_max
  - number.b4_occupancy_presence_detection_timeout
  - number.sonoff_snzb_06p_presence_detection_timeout
  - number.b6_occupancy_presence_detection_timeout_2
  - number.b7_occupancy_presence_detection_timeout_2
  - number.unknown_presence_detection_timeout_3
  - number.b12_occupancy_presence_detection_timeout_3
  - number.a6_occupancy_presence_detection_timeout_4
  - select.ikea_power_socket_1_start_up_behavior
  - select.ikea_tradfri_driver_1_start_up_behavior
  - select.ikea_tradfri_driver_2_start_up_behavior_2
  - select.ikea_power_socket_2_start_up_behavior
  - select.sonoff_snzb_02d_temp_humidity_display_unit
  - select.sonoff_snzb_02d_humid_temp_display_unit
  - select.sonoff_snzb_02d_temp_humid_display_unit
  - select.sonoff_snzb_02d_humid_temp_display_unit_2
  - select.ikea_power_socket_start_up_behavior
  - select.sonoff_snzb_02d_humid_temp_display_unit_3
  - select.sonoff_snzb_02d_humid_temp_display_unit_4
  - select.ikea_of_sweden_tretakt_smart_plug_start_up_behavior
  - select.sonoff_snzb_02d_humid_temp_display_unit_5
  - select.sonoff_snzb_02d_humid_temp_display_unit_6
  - select.ikea_of_sweden_tradfri_driver_30w_3_start_up_behavior
  - select.ikea_tradfri_driver_4_laser_cutter_start_up_behavior
  - select.ikea_tradfri_driver_4_start_up_behavior
  - select.b3_occupancy_detection_sensitivity
  - select.sonoff_snzb_02d_display_unit
  - select.b4_occupancy_detection_sensitivity
  - select.sonoff_snzb_06p_detection_sensitivity
  - select.b6_occupancy_detection_sensitivity_2
  - select.b7_occupancy_detection_sensitivity_2
  - select.unknown_detection_sensitivity_3
  - select.b12_occupancy_detection_sensitivity_3
  - select.a6_occupancy_detection_sensitivity_4
  - select.smart_switch_led_2_start_up_behaviour
  - sensor.ikea_aq_sensor_temperature
  - sensor.ikea_aq_sensor_pm2_5
  - sensor.ikea_aq_sensor_humidity
  - sensor.ikea_aq_sensor_voc_index
  - sensor.sonoff_snzb_02d_temp_humidity_battery
  - sensor.sonoff_snzb_02d_humid_temp_battery
  - sensor.sonoff_snzb_02d_humid_temp_temperature
  - sensor.sonoff_snzb_02d_humid_temp_humidity
  - sensor.sonoff_snzb_02d_temp_humid_battery
  - sensor.sonoff_snzb_02d_temp_humid_temperature
  - sensor.sonoff_snzb_02d_temp_humid_humidity
  - sensor.sonoff_snzb_02d_battery
  - sensor.sonoff_snzb_02d_temperature
  - sensor.sonoff_snzb_02d_humidity
  - sensor.sonoff_snzb_02d_humid_temp_battery_2
  - sensor.sonoff_snzb_02d_humid_temp_temperature_2
  - sensor.sonoff_snzb_02d_humid_temp_humidity_2
  - sensor.sonoff_snzb_02d_battery_2
  - sensor.sonoff_snzb_02d_temperature_2
  - sensor.sonoff_snzb_02d_humidity_2
  - sensor.sonoff_snzb_02d_humid_temp_battery_3
  - sensor.sonoff_snzb_02d_humid_temp_temperature_3
  - sensor.sonoff_snzb_02d_humid_temp_humidity_3
  - sensor.sonoff_snzb_02d_battery_3
  - sensor.sonoff_snzb_02d_temperature_3
  - sensor.sonoff_snzb_02d_humidity_3
  - sensor.b3_occupancy_last_illumination_state
  - sensor.sonoff_snzb_02d_battery_4
  - sensor.sonoff_snzb_02d_temperature_4
  - sensor.sonoff_snzb_02d_humidity_4
  - sensor.b4_occupancy_last_illumination_state
  - sensor.sonoff_snzb_06p_last_illumination_state
  - sensor.b6_occupancy_last_illumination_state_2
  - sensor.b7_occupancy_last_illumination_state_2
  - sensor.unknown_last_illumination_state_3
  - sensor.b12_occupancy_last_illumination_state_3
  - sensor.a6_occupancy_last_illumination_state_4
  - sensor.ewelink_ms01_battery
  - sensor.frient_a_s_aqszb_110_battery
  - sensor.frient_a_s_aqszb_110_temperature
  - sensor.frient_a_s_aqszb_110_humidity
  - sensor.ewelink_ms01_battery_2
  - sensor.unk_manufacturer_unk_model_battery
  - sensor.ewelink_ms01_battery_3
  - switch.ikea_power_socket_1_switch
  - switch.ikea_power_socket_2_switch
  - switch.ikea_of_sweden_tretakt_smart_plug_switch
  - switch.smart_switch_led_2
  - update.ikea_power_socket_1_firmware
  - update.ikea_aq_sensor_firmware
  - update.ikea_tradfri_driver_1_firmware
  - update.ikea_tradfri_driver_2_firmware_2
  - update.ikea_of_sweden_remote_control_n2_firmware
  - update.ikea_power_socket_2_firmware
  - update.sonoff_snzb_02d_temp_humidity_firmware
  - update.sonoff_snzb_02d_humid_temp_firmware
  - update.sonoff_snzb_02d_temp_humid_firmware
  - update.sonoff_snzb_02d_firmware
  - update.ikea_power_socket_firmware
  - update.sonoff_snzb_02d_humid_temp_firmware_2
  - update.sonoff_snzb_02d_firmware_2
  - update.ikea_of_sweden_tretakt_smart_plug_firmware
  - update.al001_wg001_z01_wifi_extender_firmware
  - update.sonoff_snzb_02d_humid_temp_firmware_3
  - update.sonoff_snzb_02d_firmware_3
  - update.ikea_of_sweden_tradfri_driver_30w_3_firmware
  - update.ikea_tradfri_driver_4_laser_cutter_firmware
  - update.ikea_tradfri_driver_4_firmware
  - update.b3_occupancy_firmware
  - update.sonoff_snzb_02d_firmware_4
  - update.b4_occupancy_firmware
  - update.sonoff_snzb_06p_firmware
  - update.b6_occupancy_firmware_2
  - update.b7_occupancy_firmware_2
  - update.unknown_firmware_3
  - update.b12_occupancy_firmware_3
  - update.a6_occupancy_firmware_4
  - update.smart_switch_led_2_firmware_2
  - update.frient_a_s_aqszb_110_firmware
  - automation.new_bottle
  - sensor.hp_envy_4520_series_black_ink
  - sensor.hp_envy_4520_series_tri_color_ink
  - sensor.local_raw_printer
  - update.kiosk_mode_update
  Lab:
  - device_tracker.smaller_black_slab
  - sensor.smaller_black_slab_storage
  - sensor.smaller_black_slab_battery_state
  - sensor.smaller_black_slab_battery_level
  - sensor.smaller_black_slab_ssid
  - sensor.smaller_black_slab_sim_2
  - sensor.smaller_black_slab_sim_1
  - sensor.smaller_black_slab_geocoded_location
  - sensor.smaller_black_slab_bssid
  - sensor.smaller_black_slab_connection_type
  - sensor.smaller_black_slab_last_update_trigger
  - sensor.smaller_black_slab_app_version
  - sensor.smaller_black_slab_location_permission
  - sensor.smaller_black_slab_audio_output
  Room:
  - sensor.unoccupied_rooms
  - binary_sensor.unoccupied_rooms
  Space:
  - person.makerspace
  - zone.home
  - weather.forecast_home
  - binary_sensor.makerspace_occupancy_occupancy
  - button.makerspace_occupancy_identify
  - light.generic_zigbee_coordinator_ezsp_makerspace_lights
  - number.makerspace_occupancy_presence_detection_timeout
  - select.makerspace_occupancy_detection_sensitivity
  - sensor.makerspace_occupancy_last_illumination_state
  - sensor.ikea_of_sweden_remote_control_n2_battery
  - sensor.sonoff_snzb_02d_temp_humidity_temperature
  - sensor.sonoff_snzb_02d_temp_humidity_humidity
  - switch.generic_zigbee_coordinator_ezsp_makerspace_lights
  - update.makerspace_occupancy_firmware
  - automation.ikea_switch_maker_space_lights_on
  - automation.ikea_switch_makerspace_lights_off
  - automation.makerspace_presence_lights_on
  - automation.makerspace_presence_lights_off
